import 'dart:convert';
import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../core/constants/app_constants.dart';
import '../models/auth_model.dart';

/// Handles OTP-based authentication.
///
/// Currently uses local simulation (no real SMS gateway).
/// To integrate a real API, replace the two marked TODO blocks in
/// [requestOtp] and [verifyOtp] — everything else stays the same.
class AuthService {
  // In-memory store for the generated OTP (cleared after verify or new request)
  String? _pendingOtp;
  String? _pendingMobile;

  // ── OTP request ────────────────────────────────────────────────────────────

  /// Sends an OTP to [mobileNumber].
  ///
  /// Returns the generated code in local/debug mode so the UI can display it.
  /// Returns null when a real API is used (code is delivered via SMS).
  Future<String?> requestOtp(String mobileNumber) async {
    // TODO: Replace with real API call →
    //   await _dio.post('/auth/send-otp', data: {'mobile': mobileNumber});
    //   return null; // code is sent via SMS, not returned
    final code = _generateOtp();
    _pendingOtp = code;
    _pendingMobile = mobileNumber;
    debugPrint('[OTP] ── Your verification code: $code ──');
    return code; // remove this line when switching to real API
  }

  // ── OTP verification ───────────────────────────────────────────────────────

  /// Verifies [otp] for [mobileNumber].
  ///
  /// Returns an [AuthUser] on success, null on failure.
  /// Local mode: compares against the in-memory code generated by [requestOtp].
  Future<AuthUser?> verifyOtp(String mobileNumber, String otp) async {
    // TODO: Replace with real API call →
    //   final res = await _dio.post('/auth/verify-otp',
    //       data: {'mobile': mobileNumber, 'otp': otp});
    //   final token = res.data['token'] as String;
    //   final userId = res.data['user_id'] as String;
    //   return AuthUser(userId: userId, mobileNumber: mobileNumber, token: token);

    if (_pendingMobile != mobileNumber || _pendingOtp != otp) {
      return null;
    }
    _pendingOtp = null;
    _pendingMobile = null;

    final user = AuthUser(
      userId: 'local_$mobileNumber',
      mobileNumber: mobileNumber,
      token: 'local_token_${DateTime.now().millisecondsSinceEpoch}',
    );
    return user;
  }

  // ── Persistence ────────────────────────────────────────────────────────────

  Future<void> saveUser(AuthUser user) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(AppConstants.prefAuthToken, user.token);
    await prefs.setString(AppConstants.prefUserId, user.userId);
    await prefs.setString(AppConstants.prefMobileNumber, user.mobileNumber);
    // Store full user as JSON for easy retrieval
    await prefs.setString(AppConstants.prefAuthUser, jsonEncode(user.toJson()));
  }

  Future<AuthUser?> loadUser() async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(AppConstants.prefAuthUser);
    if (raw == null) return null;
    try {
      return AuthUser.fromJson(jsonDecode(raw) as Map<String, dynamic>);
    } catch (e) {
      debugPrint('[AuthService] Failed to load user: $e');
      return null;
    }
  }

  Future<void> clearUser() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(AppConstants.prefAuthToken);
    await prefs.remove(AppConstants.prefUserId);
    await prefs.remove(AppConstants.prefMobileNumber);
    await prefs.remove(AppConstants.prefAuthUser);
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  String _generateOtp() {
    final rng = Random.secure();
    return List.generate(6, (_) => rng.nextInt(10)).join();
  }
}
